### ISSUE TITLE
Support LoadGltfs to load dynamic list of assets

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-ecsy-babylon#9]
The current API requires key-value pairs of assets to be passed as component arguments:

```hbs
<World.LoadGltfs
  @bedmodel={{this.bedmodelFile}}
  @material={{this.materialFile}}
  @material_base={{this.baseMaterialFile}}
  as |ach|>
```

But what if the assets are dynamic, like a map/hash of assets we don't know beforehand. We have no splarguments syntax available...

```hbs
<World.LoadGltfs
  ...this.assetMap
  as |ach|>
```

So need some other API, like:

```hbs
<World.LoadGltfs
  @assets={{this.assetMap}}
  as |ach|>
```

If we have that API, the former one is a bit redundant, as you could also do:

```hbs
<World.LoadGltfs
  @assets={{hash
    bedmodel=this.bedmodelFile
    material=this.materialFile
    material_base=this.baseMaterialFile
  }}
  as |ach|>
```

**Comment by nickschot** [comment]
Doing that splargument thing would mean more AST hackery (for now?) so I'd lean towards the latter solution. Should be a minor change and even simplify implementation as we don't have to strip the yielded arguments from this.args.
